name: "Test"

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: "Install Node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Install Deps"
        run: npm install
      - name: "Test"
        run: npx vitest --coverage
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
      - name: npm install, build
          run: npm run build
        - name: run Lighthouse CI
          run: |
            npm install -g @lhci/cli@0.12.x
            lhci autorun
