name: "Test"

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: "Install Deps"
        run: npm install
      - name: "Test"
        run: npx vitest --coverage
  conventional-changelog:
    runs-on: ubuntu-latest
    permissions:
      # Required to checkout the code
      contents: write
    steps:
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
  lighthouseci:
    runs-on: ubuntu-latest
    permissions:
      # Required to checkout the code
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install && npm install -g @lhci/cli@0.12.x
      - run: npm run build
      - run: lhci autorun
